# @package _global_

defaults:
  - _self_
  - data: cifar10 # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar10
  - logger: null
  - trainer: default
  - paths: default
  - hydra: default

task_name: "eval"

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

